name: Golang

on:
  push:
    branches: [ master ]

jobs:
  go-cmd:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - name: goCmd Test ^github.com 
        run: |
          . .\language\golang\goCmd.ps1
          Get-GO-Repos github.com/davidkhala/chaincode
          Remove-GO-Repos github.com/davidkhala/chaincode
      - name: goCmd Test ^https:// .git$
        run: |
          . .\language\golang\goCmd.ps1
          Get-GO-Repos https://github.com/davidkhala/chaincode.git
          Remove-GO-Repos https://github.com/davidkhala/chaincode.git
      - name: goCmd Test ^https://
        run: |
          . .\language\golang\goCmd.ps1
          Get-GO-Repos https://github.com/davidkhala/chaincode
          Remove-GO-Repos https://github.com/davidkhala/chaincode
        

      
