# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 
      uses: actions/setup-node@main
      with:
        node-version: lts/*
    - name: Display npm global
      run: echo "%AppData%\npm\node_modules"
    
