name: vcpkg
on: [workflow_dispatch, push]
jobs:
  release:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v4
      with:
        repository: 'microsoft/vcpkg'
    - run: bootstrap-vcpkg.bat
      shell: cmd
    - uses: softprops/action-gh-release@master
      with: 
        body: latest build of vcpkg
        name: nightly
        tag_name: latest
        files: vcpkg.exe


