name: vcpkg
on: [workflow_dispatch]
jobs:
  release:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@main
      with:
        repository: 'microsoft/vcpkg'
    - run: bootstrap-vcpkg.bat
      shell: cmd
    - run: gh release delete vcpkg --repo ${{ github.repository }} --cleanup-tag --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    - uses: softprops/action-gh-release@master
      with: 
        name: vcpkg
        files: vcpkg.exe
        tag_name: vcpkg


